import Foundation

/// A spell as heroes4.exe keeps it (records at 0xac75d0 + id x 0x88, from table.Spells): school,
/// level, mana cost, power (base + increment x caster level, before the power percentage),
/// the summoned creature, the kind and the flag names (Cmb combat, Adv adventure, Teach teachable
/// in shrines and guilds, HiPri, Mass, Resisted, ...).
public struct SpellDef {
    public let keyword: String, name: String, school: String
    public let level: Int, cost: Int, base: Int, increment: Int
    public let creature: String, kind: String, flags: String
    public func has(_ flag: String) -> Bool { flags.split(separator: " ").contains { $0 == flag } }
    public var schoolSkill: Int { ["life": 4, "order": 5, "death": 6, "chaos": 7, "nature": 8][school] ?? -1 }
}

extension RuleTables {
    /// The spells by id (heroes4.exe's table at 0x994ac0; 218 ids).
    public static let spells: [SpellDef] = [
        .init(keyword: "acid", name: "Acid", school: "chaos", level: 1, cost: 2, base: 100, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Bodies Elem Enemy Mech Undead Default Def"),
        .init(keyword: "aging", name: "Aging", school: "death", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "", flags: "Cmb Curse Enemy Friend Resisted"),
        .init(keyword: "animate dead", name: "Animate Dead", school: "death", level: 2, cost: 3, base: 50, increment: 5, creature: "", kind: "summoning", flags: "Cmb Summ Bodies Enemy Friend Undead Default Teach HiPri"),
        .init(keyword: "anti magic", name: "Anti-Magic", school: "nature", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default NoDispel Teach Def Magic"),
        .init(keyword: "armageddon", name: "Armageddon", school: "chaos", level: 5, cost: 12, base: 40, increment: 4, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Mech Undead Teach HiPri Mass"),
        .init(keyword: "banish", name: "Banish", school: "order", level: 3, cost: 5, base: 110, increment: 11, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Default Teach Magic Off"),
        .init(keyword: "berserk", name: "Berserk", school: "order", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Enemy Default Mind Resisted Teach HiPri Off"),
        .init(keyword: "bind flyer", name: "Bind Flyer", school: "order", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Default Off"),
        .init(keyword: "bind wound", name: "Bind Wound", school: "life", level: 1, cost: 2, base: 30, increment: 3, creature: "", kind: "healing", flags: "Adv Bless Cmb Friend Default Heal Teach HiPri"),
        .init(keyword: "binding", name: "Binding", school: "nature", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "", flags: "Cmb Curse Elem Enemy Mech Undead NoDispel"),
        .init(keyword: "bless", name: "Bless", school: "life", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Default Teach HiPri Off"),
        .init(keyword: "blind", name: "Blind", school: "order", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Default LoS Resisted Teach HiPri Off"),
        .init(keyword: "bloodfrenzy", name: "Bloodfrenzy", school: "chaos", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mind Teach HiPri Mass Off"),
        .init(keyword: "bloodlust", name: "Bloodlust", school: "chaos", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Default Mind Teach HiPri Off"),
        .init(keyword: "burning hands", name: "Sparks", school: "chaos", level: 1, cost: 2, base: 20, increment: 2, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Mech Undead Teach HiPri"),
        .init(keyword: "cancellation", name: "Cancellation", school: "death", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Default Teach Magic Off"),
        .init(keyword: "celestial armor", name: "Heavenly Shield", school: "life", level: 2, cost: 3, base: 50, increment: 5, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Teach HiPri Def"),
        .init(keyword: "chain lightning", name: "Chain Lightning", school: "chaos", level: 5, cost: 12, base: 80, increment: 8, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Mech Undead Default LoS Teach HiPri"),
        .init(keyword: "clone", name: "Phantom Image", school: "order", level: 4, cost: 8, base: 80, increment: 8, creature: "", kind: "summoning", flags: "Cmb Summ Elem Enemy Friend Mech Undead Default Teach HiPri"),
        .init(keyword: "cloud of confusion", name: "Cloud of Confusion", school: "chaos", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Enemy Default LoS Mind Resisted Teach HiPri Mass Off"),
        .init(keyword: "cold resistance", name: "Cold Resistance", school: "life", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Def Magic"),
        .init(keyword: "confusion", name: "Confusion", school: "chaos", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Enemy Default LoS Mind Resisted Teach HiPri Off"),
        .init(keyword: "cowardice", name: "Cowardice", school: "order", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Enemy Default Mind Resisted Teach HiPri Off"),
        .init(keyword: "curse", name: "Curse", school: "death", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Default Resisted Teach HiPri Off"),
        .init(keyword: "death call", name: "Death Call", school: "death", level: 4, cost: 8, base: 90, increment: 9, creature: "", kind: "summoning", flags: "Cmb Summ Bodies Enemy Friend Undead Default Teach HiPri"),
        .init(keyword: "despair", name: "Despair", school: "death", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Enemy Default Resisted Off"),
        .init(keyword: "disintegrate", name: "Disintegrate", school: "chaos", level: 5, cost: 12, base: 110, increment: 11, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Mech Undead Default LoS Teach HiPri"),
        .init(keyword: "dispel", name: "Dispel", school: "order", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Curse Elem Enemy Friend Mech Undead Default Teach Def Magic"),
        .init(keyword: "displacement", name: "Displacement", school: "order", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Curse Elem Enemy Friend Mech Undead Default ResIfEnemy Teach Off"),
        .init(keyword: "divine aura", name: "Celestial Armor", school: "life", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Teach HiPri Def Mass"),
        .init(keyword: "divine intervention", name: "Divine Intervention", school: "life", level: 5, cost: 12, base: 50, increment: 5, creature: "", kind: "healing", flags: "Adv Bless Cmb Bodies Elem Friend Mech Undead Teach HiPri Mass"),
        .init(keyword: "divine protection", name: "Defender", school: "life", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Teach Mass"),
        .init(keyword: "divine retribution", name: "Holy Shout", school: "life", level: 3, cost: 5, base: 30, increment: 3, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Mech Undead Teach Mass"),
        .init(keyword: "dragon strength", name: "Dragon Strength", school: "nature", level: 5, cost: 12, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach HiPri Def Off"),
        .init(keyword: "evil hour", name: "Unholy Song", school: "death", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Friend Resisted Teach Mass Off"),
        .init(keyword: "exorcism", name: "Exorcism", school: "life", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach Def Magic"),
        .init(keyword: "fear", name: "Aura of Fear", school: "death", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Enemy Friend Mech Undead Default Teach HiPri Off"),
        .init(keyword: "fear_effect", name: "not applicable", school: "death", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: "Enemy Friend Fear Mind Resisted"),
        .init(keyword: "fire_aura_effect", name: "not applicable", school: "chaos", level: 1, cost: 0, base: 10, increment: 1, creature: "", kind: "", flags: "Elem Enemy Friend Mech Undead Fire"),
        .init(keyword: "fire bolt", name: "Fire Bolt", school: "chaos", level: 2, cost: 3, base: 50, increment: 5, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Mech Undead Default Fire LoS Teach HiPri"),
        .init(keyword: "fire resistance", name: "Fire Resistance", school: "life", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Def Magic"),
        .init(keyword: "fire ring", name: "Fire Ring", school: "chaos", level: 3, cost: 5, base: 40, increment: 4, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Mech Undead Default Fire LoS Teach HiPri"),
        .init(keyword: "fire shield", name: "Fire Shield", school: "chaos", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "", flags: "Bless Cmb Elem Enemy Friend Mech Undead Fire"),
        .init(keyword: "fireball", name: "Fireball", school: "chaos", level: 3, cost: 5, base: 40, increment: 4, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Mech Undead Default Fire LoS Teach HiPri"),
        .init(keyword: "firebreathing", name: "Fire Aura", school: "chaos", level: 1, cost: 2, base: 10, increment: 1, creature: "", kind: "damage", flags: "Bless Cmb Elem Friend Mech Undead Default Teach HiPri"),
        .init(keyword: "first strike", name: "First Strike", school: "chaos", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach HiPri Off"),
        .init(keyword: "flight", name: "Flight", school: "order", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach Off"),
        .init(keyword: "forgetfulness", name: "Forgetfulness", school: "order", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Enemy Default Mind Resisted Teach HiPri Off"),
        .init(keyword: "fortune", name: "Fortune", school: "nature", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach HiPri Def"),
        .init(keyword: "freeze", name: "Freezing Attack", school: "order", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Adv Bless Cmb Elem Friend Mech Undead Off"),
        .init(keyword: "choking gas", name: "Choking Gas", school: "death", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Enemy Friend Default Resisted Def Off"),
        .init(keyword: "giant strength", name: "Giant Strength", school: "nature", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach HiPri Def Off"),
        .init(keyword: "greater forgetfulness", name: "Mass Forgetfulness", school: "order", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "", flags: "Cmb Curse Enemy Mind Resisted"),
        .init(keyword: "guardian angel", name: "Guardian Angel", school: "life", level: 5, cost: 12, base: 1, increment: 1, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach HiPri Def"),
        .init(keyword: "hand of death", name: "Hand of Death", school: "death", level: 5, cost: 12, base: 1, increment: 1, creature: "", kind: "hand_of_death", flags: "Cmb Curse Enemy Friend Default LoS Resisted Teach HiPri"),
        .init(keyword: "haste", name: "Haste", school: "chaos", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach HiPri Off"),
        .init(keyword: "heal", name: "Heal", school: "life", level: 2, cost: 3, base: 50, increment: 5, creature: "", kind: "healing", flags: "Adv Bless Cmb Friend Default Heal Teach HiPri"),
        .init(keyword: "health boost", name: "Health", school: "nature", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Adv Bless Cmb Friend Def"),
        .init(keyword: "holy armor", name: "Spiritual Armor", school: "life", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach HiPri Def"),
        .init(keyword: "holy retribution", name: "Retribution", school: "life", level: 2, cost: 3, base: 10, increment: 1, creature: "", kind: "damage", flags: "Bless Cmb Elem Enemy Friend Mech Undead Default Teach HiPri"),
        .init(keyword: "holy water", name: "Holy Water", school: "life", level: 2, cost: 3, base: 45, increment: 4, creature: "", kind: "damage", flags: "Bless Cmb Curse Elem Enemy Friend Mech Undead Default LoS"),
        .init(keyword: "holy word", name: "Holy Word", school: "life", level: 1, cost: 2, base: 45, increment: 4, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Undead Default Resisted Teach"),
        .init(keyword: "hypnotize", name: "Hypnotize", school: "order", level: 5, cost: 12, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Enemy Default Mind Resisted Teach HiPri Off"),
        .init(keyword: "ice bolt", name: "Ice Bolt", school: "order", level: 2, cost: 3, base: 40, increment: 4, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Mech Undead Default Cold LoS Teach HiPri"),
        .init(keyword: "illusionary ally", name: "Create Illusion", school: "order", level: 2, cost: 3, base: 40, increment: 4, creature: "", kind: "summoning", flags: "Cmb Summ Elem Enemy Friend Mech Undead Default Teach HiPri"),
        .init(keyword: "implosion", name: "Implosion", school: "chaos", level: 4, cost: 8, base: 90, increment: 9, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Mech Undead Default LoS Teach HiPri"),
        .init(keyword: "inferno", name: "Inferno", school: "chaos", level: 4, cost: 8, base: 40, increment: 4, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Mech Undead Fire LoS Teach HiPri"),
        .init(keyword: "kreegan fire", name: "Demon Fire", school: "chaos", level: 1, cost: 2, base: 30, increment: 0, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Mech Undead Default Fire LoS"),
        .init(keyword: "life drain", name: "Life Drain", school: "death", level: 2, cost: 3, base: 10, increment: 1, creature: "", kind: "damage", flags: "Cmb Dmg Enemy Friend Resisted Teach Mass"),
        .init(keyword: "lightning", name: "Lightning", school: "chaos", level: 3, cost: 5, base: 70, increment: 7, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Mech Undead Default LoS Teach HiPri"),
        .init(keyword: "luck", name: "Luck", school: "nature", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Adv Bless Cmb Elem Friend Mech Undead Def"),
        .init(keyword: "magic arrow", name: "Magic Arrow", school: "chaos", level: 1, cost: 2, base: 30, increment: 3, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Mech Undead Default LoS Teach HiPri"),
        .init(keyword: "magic fist", name: "Magic Fist", school: "order", level: 1, cost: 2, base: 20, increment: 2, creature: "", kind: "damage", flags: "Cmb Dmg Elem Enemy Friend Mech Undead Default LoS Teach HiPri"),
        .init(keyword: "magic leech", name: "Magic Leech", school: "death", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Default Resisted Teach Magic Off"),
        .init(keyword: "magic mirror", name: "Magic Mirror", school: "chaos", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach Def Magic"),
        .init(keyword: "magic resistance", name: "Magic Resistance", school: "nature", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Def Magic"),
        .init(keyword: "mana", name: "Mana", school: "chaos", level: 1, cost: 2, base: 25, increment: 0, creature: "", kind: "mana", flags: "Adv Bless Cmb Elem Friend Mech Undead"),
        .init(keyword: "mana flare", name: "Mana Flare", school: "chaos", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Enemy Friend Mech Undead Teach Magic Mass Off"),
        .init(keyword: "mana_leech", name: "Mana Leech", school: "death", level: 1, cost: 0, base: 2, increment: 0, creature: "", kind: "", flags: "Curse Elem Enemy Friend Mech Undead Resisted"),
        .init(keyword: "martyr", name: "Martyr", school: "life", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach Def"),
        .init(keyword: "mass bless", name: "Mass Bless", school: "life", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Teach HiPri Mass Off"),
        .init(keyword: "mass cancellation", name: "Mass Cancellation", school: "death", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Teach Magic Off"),
        .init(keyword: "mass curse", name: "Mass Curse", school: "death", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Resisted Teach HiPri Mass"),
        .init(keyword: "mass dispel", name: "Mass Dispel", school: "order", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "curse", flags: "Bless Cmb Curse Elem Enemy Friend Mech Undead Teach Magic Mass Off"),
        .init(keyword: "mass exorcism", name: "Mass Exorcism", school: "life", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Teach Def Magic Mass"),
        .init(keyword: "mass first strike", name: "Mass First Strike", school: "chaos", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Teach HiPri Mass Off"),
        .init(keyword: "mass fortune", name: "Mass Fortune", school: "nature", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Teach HiPri Def Mass"),
        .init(keyword: "mass haste", name: "Mass Speed", school: "nature", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Teach HiPri Mass Off"),
        .init(keyword: "mass healing", name: "Mass Healing", school: "life", level: 3, cost: 5, base: 25, increment: 2, creature: "", kind: "healing", flags: "Adv Bless Cmb Friend Heal Teach HiPri Mass"),
        .init(keyword: "mass misfortune", name: "Mass Misfortune", school: "chaos", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Resisted Teach HiPri Def Mass"),
        .init(keyword: "mass precision", name: "Mass Precision", school: "order", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Friend Mind Teach HiPri Mass Off"),
        .init(keyword: "mass protection from chaos", name: "Mass Chaos Ward", school: "life", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Teach Def Mass"),
        .init(keyword: "mass protection from death", name: "Mass Death Ward", school: "life", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Teach Def Mass"),
        .init(keyword: "mass protection from nature", name: "Mass Nature Ward", school: "life", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Teach Def Mass"),
        .init(keyword: "mass protection from order", name: "Mass Order Ward", school: "life", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Teach Def Mass"),
        .init(keyword: "mass slayer", name: "Mass Slayer", school: "chaos", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Teach Mass Off"),
        .init(keyword: "mass slow", name: "Mass Slow", school: "order", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Resisted Teach HiPri Mass Off"),
        .init(keyword: "mass snake strike", name: "Mass Snake Strike", school: "nature", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Teach HiPri Mass Off"),
        .init(keyword: "mass sorrow", name: "Mass Sorrow", school: "death", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Enemy Mind Resisted Teach HiPri Mass Off"),
        .init(keyword: "mass spiritual fervor", name: "Mass Fervor", school: "life", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Friend Mind Teach HiPri Mass Off"),
        .init(keyword: "mass weakness", name: "Mass Weakness", school: "death", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Resisted Teach HiPri Mass Off"),
        .init(keyword: "mire", name: "Mire", school: "death", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "", flags: "Adv Elem Enemy Undead Default Resisted Teach"),
        .init(keyword: "misfortune", name: "Misfortune", school: "chaos", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Default Resisted Teach HiPri Def"),
        .init(keyword: "morale", name: "Morale", school: "life", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Adv Bless Cmb Friend Mind Off"),
        .init(keyword: "nature haste", name: "Speed", school: "nature", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach HiPri Off"),
        .init(keyword: "order slow", name: "Slow", school: "order", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Default Resisted Teach HiPri Off"),
        .init(keyword: "pain mirror", name: "Pain Mirror", school: "order", level: 5, cost: 12, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Enemy Friend Mech Undead Default Teach HiPri Def"),
        .init(keyword: "panic", name: "Panic", school: "death", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "", flags: "Bless Cmb Enemy Fear Mind Resisted"),
        .init(keyword: "pathfinding", name: "Pathfinding", school: "nature", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "", flags: "Adv Elem Friend Mech Undead Teach"),
        .init(keyword: "blur", name: "Blur", school: "order", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach HiPri Def"),
        .init(keyword: "plague", name: "Plague", school: "death", level: 3, cost: 5, base: 10, increment: 1, creature: "", kind: "damage", flags: "Cmb Curse Dmg Enemy Friend NoDispel Resisted Teach HiPri Mass"),
        .init(keyword: "poison", name: "Poison", school: "death", level: 1, cost: 2, base: 10, increment: 1, creature: "", kind: "damage", flags: "Cmb Curse Dmg Enemy Default NoDispel Resisted Teach HiPri"),
        .init(keyword: "poison attack", name: "Poison Attack", school: "death", level: 1, cost: 2, base: 10, increment: 1, creature: "", kind: "damage", flags: "Bless Cmb Elem Enemy Friend Mech Undead NoDispel"),
        .init(keyword: "power drain", name: "Power Drain", school: "order", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Default Resisted Teach Magic Off"),
        .init(keyword: "prayer", name: "Prayer", school: "life", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Enemy Friend Mech Undead Teach HiPri Def Mass Off"),
        .init(keyword: "precision", name: "Precision", school: "order", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Default Mind Teach HiPri Off"),
        .init(keyword: "immortality", name: "Immortality", school: "life", level: 5, cost: 12, base: 1, increment: 0, creature: "", kind: "blessing", flags: "Adv Bless Cmb Elem Friend Mech Undead Def"),
        .init(keyword: "protection from chaos", name: "Chaos Ward", school: "life", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach Def"),
        .init(keyword: "protection from death", name: "Death Ward", school: "life", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach Def"),
        .init(keyword: "protection from life", name: "Life Ward", school: "life", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Def"),
        .init(keyword: "protection from nature", name: "Nature Ward", school: "life", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach Def"),
        .init(keyword: "protection from order", name: "Order Ward", school: "life", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach Def"),
        .init(keyword: "quickness", name: "Quickness", school: "chaos", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Off"),
        .init(keyword: "quicksand", name: "Quicksand", school: "nature", level: 2, cost: 3, base: 20, increment: 0, creature: "", kind: "", flags: "Cmb Default Teach HiPri"),
        .init(keyword: "raise ghost", name: "Raise Ghost", school: "death", level: 3, cost: 5, base: 150, increment: 15, creature: "ghost", kind: "summoning", flags: "Cmb Summ Bodies Enemy Friend Undead NoDispel Teach HiPri"),
        .init(keyword: "raise skeletons", name: "Raise Skeletons", school: "death", level: 1, cost: 2, base: 40, increment: 4, creature: "skeleton", kind: "summoning", flags: "Cmb Summ Bodies Enemy Friend Undead Default NoDispel Teach HiPri"),
        .init(keyword: "raise vampires", name: "Raise Vampires", school: "death", level: 5, cost: 12, base: 375, increment: 37, creature: "vampire", kind: "summoning", flags: "Cmb Summ Bodies Enemy Friend Undead Teach HiPri"),
        .init(keyword: "mass_blur", name: "Mass Blur", school: "order", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead NoDispel Teach HiPri Def Mass"),
        .init(keyword: "ray of suffering", name: "Disrupting Ray", school: "death", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Default Resisted Teach HiPri Def"),
        .init(keyword: "rebirth", name: "Rebirth", school: "life", level: 5, cost: 12, base: 55, increment: 0, creature: "", kind: "resurrection", flags: "Bless Cmb Bodies Friend Heal"),
        .init(keyword: "reflexes", name: "Cat Reflexes", school: "chaos", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach HiPri Off"),
        .init(keyword: "regeneration", name: "Regeneration", school: "life", level: 3, cost: 5, base: 20, increment: 2, creature: "", kind: "healing", flags: "Adv Bless Cmb Friend Default Heal Teach HiPri"),
        .init(keyword: "endurance", name: "Endurance", school: "nature", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "", flags: "Adv Elem Friend Mech Undead"),
        .init(keyword: "resurrection", name: "Resurrection", school: "life", level: 5, cost: 20, base: 92, increment: 0, creature: "", kind: "resurrection", flags: "Bless Cmb Bodies Friend Default Heal"),
        .init(keyword: "rock growth", name: "Rock Growth", school: "nature", level: 2, cost: 3, base: 80, increment: 8, creature: "", kind: "", flags: "Cmb Summ Default"),
        .init(keyword: "sacred ground", name: "Necromancy Ward", school: "nature", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Bodies Enemy Friend Undead Teach Def Magic Mass"),
        .init(keyword: "sacrifice", name: "Sacrifice", school: "death", level: 5, cost: 12, base: 0, increment: 0, creature: "", kind: "sacrifice", flags: "Bless Cmb Friend Undead Teach HiPri"),
        .init(keyword: "sanctuary", name: "Sanctuary", school: "life", level: 5, cost: 12, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach HiPri Def"),
        .init(keyword: "short hypnotism", name: "Charm", school: "order", level: 2, cost: 5, base: 0, increment: 0, creature: "", kind: "", flags: "Cmb Curse Enemy Mind"),
        .init(keyword: "simple healing", name: "Heal", school: "life", level: 1, cost: 2, base: 10000, increment: 5, creature: "", kind: "healing", flags: "Adv Bless Cmb Friend Heal"),
        .init(keyword: "slayer", name: "Slayer", school: "chaos", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach Off"),
        .init(keyword: "slow", name: "Fatigue", school: "death", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Default Resisted Teach HiPri Off"),
        .init(keyword: "smoke", name: "Smoke", school: "death", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Cmb Elem Enemy Friend Mech Undead Default Def"),
        .init(keyword: "snake strike", name: "Snake Strike", school: "nature", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach HiPri Off"),
        .init(keyword: "song of peace", name: "Song of Peace", school: "life", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Enemy Default LoS Mind Resisted Teach HiPri Off"),
        .init(keyword: "sorrow", name: "Sorrow", school: "death", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Enemy Default Mind Resisted Teach HiPri Off"),
        .init(keyword: "speed", name: "Speed Potion", school: "chaos", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Adv Bless Cmb Elem Friend Mech Undead Off"),
        .init(keyword: "spell shackle", name: "Spell Shackle", school: "chaos", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Default Resisted Teach Magic Off"),
        .init(keyword: "spiritual fervor", name: "Mirth", school: "life", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Friend Default Mind Teach HiPri Off"),
        .init(keyword: "steal all enchantments", name: "Steal All Enchantments", school: "order", level: 5, cost: 12, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Teach HiPri Magic Mass Off"),
        .init(keyword: "steal enchantment", name: "Steal Enchantment", school: "order", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Default Teach Magic Off"),
        .init(keyword: "stoneskin", name: "Stoneskin", school: "nature", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach HiPri Def"),
        .init(keyword: "stone_gaze", name: "Stone Gaze", school: "death", level: 5, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: "Cmb Curse Enemy Friend Resisted"),
        .init(keyword: "strength", name: "Strength", school: "nature", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Adv Bless Cmb Elem Friend Mech Undead Off"),
        .init(keyword: "stun", name: "Stun", school: "order", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "", flags: "Cmb Curse Enemy Default NoDispel"),
        .init(keyword: "summon elf", name: "Summon Elf", school: "nature", level: 2, cost: 3, base: 75, increment: 7, creature: "elf", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "summon tiger", name: "Summon White Tiger", school: "nature", level: 2, cost: 3, base: 75, increment: 7, creature: "white tiger", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "summon air elemental", name: "Summon Air Elemental", school: "nature", level: 3, cost: 5, base: 150, increment: 15, creature: "air elemental", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "summon boat", name: "Summon Ship", school: "life", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "", flags: "Adv Teach"),
        .init(keyword: "summon cerberus", name: "Summon Cerberus", school: "nature", level: 2, cost: 8, base: 250, increment: 25, creature: "cerberus", kind: "summoning", flags: "Cmb Summ NoDispel"),
        .init(keyword: "summon demon", name: "Summon Ice Demon", school: "death", level: 4, cost: 8, base: 157, increment: 0, creature: "ice demon", kind: "summoning", flags: "Cmb Summ NoDispel"),
        .init(keyword: "summon venom spawn", name: "Summon Venom Spawn", school: "nature", level: 4, cost: 18, base: 525, increment: 52, creature: "venom spawn", kind: "summoning", flags: "Cmb Summ NoDispel"),
        .init(keyword: "summon devils", name: "Summon Devil", school: "nature", level: 5, cost: 24, base: 675, increment: 67, creature: "archdevil", kind: "summoning", flags: "Cmb Summ NoDispel"),
        .init(keyword: "summon earth elemental", name: "Summon Earth Elemental", school: "nature", level: 3, cost: 5, base: 150, increment: 15, creature: "earth elemental", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "summon faerie dragon", name: "Summon Faerie Dragon", school: "nature", level: 5, cost: 12, base: 375, increment: 37, creature: "faerie dragon", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "summon fire elemental", name: "Summon Fire Elemental", school: "nature", level: 3, cost: 5, base: 150, increment: 15, creature: "fire elemental", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "summon griffin", name: "Summon Griffin", school: "nature", level: 4, cost: 8, base: 250, increment: 25, creature: "griffin", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "summon ice demon", name: "Summon Ice Demon", school: "nature", level: 3, cost: 12, base: 350, increment: 35, creature: "ice demon", kind: "summoning", flags: "Cmb Summ NoDispel"),
        .init(keyword: "summon imps", name: "Summon Imp", school: "nature", level: 1, cost: 5, base: 125, increment: 12, creature: "imp", kind: "summoning", flags: "Cmb Summ Elem"),
        .init(keyword: "summon leprechaun", name: "Summon Leprechaun", school: "nature", level: 1, cost: 2, base: 40, increment: 3, creature: "leprechaun", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "summon mantis", name: "Summon Mantis", school: "nature", level: 5, cost: 12, base: 375, increment: 37, creature: "mantis", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "summon phoenix", name: "Summon Phoenix", school: "nature", level: 5, cost: 12, base: 375, increment: 37, creature: "phoenix", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "summon satyr", name: "Summon Satyr", school: "nature", level: 2, cost: 3, base: 75, increment: 7, creature: "satyr", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "summon sprite", name: "Summon Sprite", school: "nature", level: 1, cost: 2, base: 40, increment: 3, creature: "sprite", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "summon stinkbug", name: "Wasp Swarm", school: "nature", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Default LoS Resisted Teach HiPri Off"),
        .init(keyword: "summon unicorn", name: "Summon Unicorn", school: "nature", level: 4, cost: 8, base: 250, increment: 25, creature: "unicorn", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "summon water elemental", name: "Summon Water Elemental", school: "nature", level: 3, cost: 5, base: 150, increment: 15, creature: "water elemental", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "summon wolf", name: "Summon Wolf", school: "nature", level: 1, cost: 2, base: 40, increment: 3, creature: "wolf", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "teleport", name: "Teleport", school: "order", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Curse Elem Enemy Friend Mech Undead Default ResIfEnemy Teach Off"),
        .init(keyword: "terrain walk", name: "Terrain Walk", school: "nature", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Friend Mech Undead Default Teach Off"),
        .init(keyword: "terror", name: "Terror", school: "death", level: 2, cost: 6, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Enemy Default Fear LoS Mind Resisted Off"),
        .init(keyword: "town gate", name: "Town Gate", school: "order", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "", flags: "Adv Bless Cmb Elem Friend Mech Undead Default Teach"),
        .init(keyword: "vampiric touch", name: "Vampiric Touch", school: "death", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Elem Enemy Friend Mech Undead Default Teach HiPri Off"),
        .init(keyword: "visions", name: "Visions", school: "order", level: 1, cost: 2, base: 0, increment: 0, creature: "", kind: "", flags: "Adv Friend Mind Teach"),
        .init(keyword: "water walk", name: "Water Walk", school: "nature", level: 3, cost: 5, base: 0, increment: 0, creature: "", kind: "", flags: "Adv Elem Friend Mech Undead"),
        .init(keyword: "weakness", name: "Weakness", school: "death", level: 2, cost: 3, base: 0, increment: 0, creature: "", kind: "curse", flags: "Cmb Curse Elem Enemy Mech Undead Default Resisted Teach HiPri Off"),
        .init(keyword: "frozen", name: "Frozen", school: "order", level: 4, cost: 8, base: 0, increment: 0, creature: "", kind: "", flags: "Adv Cmb Curse Elem Enemy Mech Undead Cold Resisted"),
        .init(keyword: "summon_waspwort", name: "Summon Waspwort", school: "nature", level: 4, cost: 8, base: 250, increment: 25, creature: "waspwort", kind: "summoning", flags: "Cmb Summ NoDispel Teach HiPri"),
        .init(keyword: "berserk_effect", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "block", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "devour", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "robe_of_the_guardian", name: "Robe of the Guardian", school: "life", level: 5, cost: 0, base: 3, increment: 0, creature: "", kind: "blessing", flags: "Bless Cmb Def"),
        .init(keyword: "hypnotize_effect", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "martyr_client", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "sacrifice_client", name: "Sacrifice", school: "death", level: 5, cost: 12, base: 0, increment: 0, creature: "", kind: "", flags: "Bless Cmb Bodies Friend Undead"),
        .init(keyword: "vampirism", name: "not applicable", school: "death", level: 4, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: "Enemy Friend Resisted"),
        .init(keyword: "acid_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "binding_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "cold_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "despair_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "endurance_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "fire_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "fire_resistance_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "gas_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "healing_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "health_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "holy_water_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "luck_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "mana_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "mirth_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "poison_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "precognition_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "quickness_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "resistance_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "restoration_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "smoke_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "speed_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
        .init(keyword: "strength_potion", name: "(no table row)", school: "", level: 0, cost: 0, base: 0, increment: 0, creature: "", kind: "", flags: ""),
    ]
    public static func spellId(_ keyword: String) -> Int? { spells.firstIndex { $0.keyword == keyword.lowercased() } }
}
